<?php

/**
 * This is the model base class for the table "test".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Test".
 *
 * Columns in table "test" available as properties of the model,
 * followed by relations of table "test" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $order
 * @property string $slug
 *
 * @property Test2[] $test2s
 */
abstract class BaseTest extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'test';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Test|Tests', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, order, slug', 'required'),
			array('order', 'numerical', 'integerOnly'=>true),
			array('name, slug', 'length', 'max'=>10),
			array('id, name, order, slug', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'test2s' => array(self::HAS_MANY, 'Test2', 'test_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'order' => Yii::t('app', 'Order'),
			'slug' => Yii::t('app', 'Slug'),
			'test2s' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('order', $this->order);
		$criteria->compare('slug', $this->slug, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}